name: Build & Push Release Docker Image
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: eeexdocker/kurgan-app-web
    steps:
      - uses: actions/checkout@v1
      - name: Docker Hub Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Building Docker Image
        run: docker build -t $REPO:${{ github.ref_name }} .
      - name: Publish Docker Image
        run: docker push $REPO:${{ github.ref_name }}
